# Jekyll Resume Theme

# Site settings
title: CV for Taehun Yang
email: thyang.spring@gmail.com
description: CV for T.Yang
baseurl: ""
url: "http://rendey.github.io"
name: Taehun Yang
job: Assistant Professor
location: Andong, S. Korea
#languages: HTML, CSS and Javascript
github_username:  rendey
linkedin_username:  taehunyang
email_address: thyang.spring@gmail.com
introduction: Taehun Yang is working as an assistant professor in Computer Engineering at Andong National University since 2023. He worked as a postdoctoral researcher at Kongju National University in 2022. He received a Ph.D. degree in Computer Engineering at Chungnam National University, in 2022. He received a B.S. degree in Computer Engineering from Chungnam National University, in 2014. His research areas are computer communication, mobile computing, wireless communication, and digital twin.

# Build settings
#markdown: kramdown
markdown: markdown
