# Jekyll Resume Theme

# Site settings
title: CV for Taehun Yang
email: thyang.spring@gmail.com
description: CV for Y
baseurl: ""
url: "http://rendey.github.io"
name: Taehun Yang
job: Ph.D
location: Daejeon, S. Korea
#languages: HTML, CSS and Javascript
#twitter_username: mattcouchman
#github_username:  mattcouchman
#codepen_username:  mattcouchman
#email_address: some@email.com

# Build settings
markdown: kramdown
