# Jekyll Resume Theme

# Site settings
title: CV for Taehun Yang
email: thyang.spring@gmail.com
description: CV for T.Yang
baseurl: ""
url: "http://rendey.github.io"
name: Taehun Yang
job: Assistant Professor
location: Andong, S. Korea
#languages: HTML, CSS and Javascript
github_username:  rendey
linkedin_username:  taehunyang
email_address: thyang.spring@gmail.com

# Build settings
markdown: kramdown
